### ISSUE TITLE
仔细看一下源码,基础是够用,提几点IISUES

### ISSUE THREAD

**Issue by qinxingnet** [hjx601496320/JdbcPlus#1]
1.annonation 建议直接使用javaee-api
2.com.hebaibai.jdbcplus.EntityMapperFactory#getMapper里的synchronized (entityTableRowMapperMap) 效率太低
3.不支持分库分表

**Comment by hjx601496320** [comment]
谢谢你提的IISUES，还是第一次有人给我提这个。我还有点激动\(≧▽≦)/，下面是我的一些看法
1.关于注解，我之前直接用的jpa里提供的注解，但是他的注解中属性太多了，我没有办法很完整的支持这些属性，后来就改成自己定义注解了。
2.com.hebaibai.jdbcplus.EntityMapperFactory#getMapper里的synchronized这一部分我改了好几次，最终这样写是因为我觉得出现效率问题只是会出现在项目刚开始启动的时候，entity对应的EntityTableRowMapper还没有创建的时候可能会慢，之后就应该不会了。
3.分库这里可以通过mycat，或者Sharding JDBC 提供DataSource就好了。
上面是我自己的一些看法，再次感谢你给我提供意见。

**Comment by qinxingnet** [comment]
有和你一样的想法试用在项目中. 原来自已也写了一个同样类似的.准备和你共建,如何? 
另外,你这个有在项目中使用吗? 还是练手的哈..别坑了兄弟们.
把count,group by基础功能都添加一下?  帮添加一下QQ 48742915

**Comment by hjx601496320** [comment]
count 这种的函数我是这么解决的，看起来有点粗糙：
```
Map<String, Object> objectMap = jdbcPlus.selectColumnForMap(MerchantPayConfig.class, ands, "count(*) as count");
long count = (long) objectMap.get("count");
```
group by 的话我看看应该怎么弄，有空了加上。
另外项目中我只是简单的用增删该查，目前没有什么问题。但是不排除哈（因为是自己写的，所以自己用心里还是有底）
再次感谢。
